// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdbicwwprbmpaaawvdua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkYmljd3dwcmJtcGFhYXd2ZHVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTk4OTcsImV4cCI6MjA2NjM3NTg5N30.vvk0-VwlORS523IBs-GH6qz79JE68c4FazE6qEGiwDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);